### ISSUE TITLE
Notes on miss-islington merging PRs are out of date

### ISSUE THREAD

**Issue by AlexWaygood** [JelleZijlstra/JelleZijlstra.github.io#2]
https://github.com/JelleZijlstra/JelleZijlstra.github.io/blob/7708be319429647203e31798163c3255c64c206e/cpython.md?plain=1#L70-L77

We use GitHub automerge now. I'd make a PR, but I don't know what your personal workflow is these days (e.g. whether you still assign backport PRs to yourself, etc. :)

**Comment by JelleZijlstra** [comment]
Yes, I think I should switch my workflow to be "click the automerge button and assign".

**Comment by JelleZijlstra** [comment]
Fixed in cae6a3aa8c9dd150c90c5f1da728b0153a1f1b48
